global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
    - to: '506741@student.saxion.nl'
      from: 'testismyonlypurpose@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      auth_username: 'testismyonlypurpose@gmail.com'
      auth_password: 'ypfp jfcz xjkl etfl'
      send_resolved: true