global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - ${eip_public_ip}:9093 

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['${eip_public_ip}:3000'] 
    metrics_path: '/api/metrics' 
